return{
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	"tpope/vim-repeat",
	"ggandor/lightspeed.nvim",
	"itchyny/lightline.vim",
	"nvim-tree/nvim-web-devicons",
	"nvim-lua/plenary.nvim",
	"nvim-telescope/telescope.nvim",
	{"nvim-treesitter/nvim-treesitter", build = ":TSUpdate", config = function() vim.cmd([[:TSEnable highlight]]) end},
	{"windwp/nvim-autopairs", event = "InsertEnter", config=true},
	"neovim/nvim-lspconfig",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-path",
	"hrsh7th/cmp-cmdline",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-vsnip",
	"hrsh7th/vim-vsnip",
	"mfussenegger/nvim-dap",
	"mattn/emmet-vim",
	"dcampos/cmp-emmet-vim",
	"ThePrimeagen/refactoring.nvim",
	"mbbill/undotree",
	"luk400/vim-jukit",
	{"github/copilot.vim", config = function() vim.cmd([[:Copilot disable]]) end},
	"williamboman/mason.nvim",
	"williamboman/mason-lspconfig.nvim",
	"inkarkat/vim-ReplaceWithRegister",
	"inkarkat/vim-ReplaceWithSameIndentRegister",
	"elihunter173/dirbuf.nvim",
	{'bennypowers/splitjoin.nvim',lazy = true,keys = {{ 'gj', function() require'splitjoin'.join() end, desc = 'Join the object under cursor' },{ 'g,', function() require'splitjoin'.split() end, desc = 'Split the object under cursor' },},}
}
