return{
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	"tpope/vim-repeat",
	"ggandor/lightspeed.nvim",
	"itchyny/lightline.vim",
	"nvim-tree/nvim-web-devicons",
	"nvim-lua/plenary.nvim",
	"nvim-telescope/telescope.nvim",
	{"nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
	{"windwp/nvim-autopairs", event = "InsertEnter", config=true},
	"neovim/nvim-lspconfig",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-path",
	"hrsh7th/cmp-cmdline",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-vsnip",
	"hrsh7th/vim-vsnip",
	"mfussenegger/nvim-dap",
	"mattn/emmet-vim",
	"dcampos/cmp-emmet-vim",
	"ThePrimeagen/refactoring.nvim",
	"mbbill/undotree",
}
